{% set version = "6.2.1" %}

package:
  name: coolprop
  version: {{ version }}

source:
  git_url: https://github.com/bryanwweber/CoolProp
  # This is version 6.2.1, but it isn't tagged
  git_tag: 81dbcb71c512b5d57cdfe197e59ae87f0221e4e6
  patches:
    - setuppy-macos.patch  # [osx]
    - CMakeLists-python.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - git
  host:
    - python
    - setuptools
    - cython

  run:
    - python

test:
  imports:
    - CoolProp
    - CoolProp.GUI
    # - CoolProp.Plots
    - CoolProp.tests

  commands:
    - python -c "from CoolProp.CoolProp import PropsSI; assert PropsSI('Phase', 'T', 300.0, 'P', 101325.0, 'Water') == 0.0"

about:
  home: http://www.coolprop.org
  license: MIT License
  summary: "Open-source thermodynamic and transport properties database"
  description: "CoolProp is a thermophysical property database and wrappers for a selection of programming environments. It offers similar functionality to REFPROP, but CoolProp is open-source and free"
  license_file: LICENSE
  license_family: MIT
  doc_url: http://coolprop.org
  dev_url: https://github.com/coolprop/coolprop
