package:
  name: coolprop
  version: "6.1.0"

source:
  git_url: https://github.com/CoolProp/CoolProp
  git_tag: v6.1.0
  patches:
    - setuppy.patch  # [win]

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - cmake

  run:
    - python
    - numpy
    # - matplotlib
    # - scipy

test:
  imports:
    - CoolProp
    - CoolProp.GUI
    # - CoolProp.Plots
    - CoolProp.tests

about:
  home: http://www.coolprop.org
  license: MIT License
  summary: 'Open-source thermodynamic and transport properties database'
