package:
  name: coolprop
  version: "6.1.0"

source:
  git_url: https://github.com/CoolProp/CoolProp
  git_tag: v6.1.0
  patches:
    - setuppy.patch  # [win]

build:
  number: 2

requirements:
  build:
    - python >=2.7,<3|>=3.3,{{PY_VER}}*
    - setuptools
    - cython
    - cmake

  run:
    - python {{PY_VER}}*

test:
  imports:
    - CoolProp
    - CoolProp.GUI
    # - CoolProp.Plots
    - CoolProp.tests

  commands:
    - python -c "from CoolProp.CoolProp import PropsSI; assert PropsSI('Phase', 'T', 300.0, 'P', 101325.0, 'Water') == 0.0"

about:
  home: http://www.coolprop.org
  license: MIT License
  summary: 'Open-source thermodynamic and transport properties database'
