package:
    name: pychempath
    version: "0.0.1"

source:
    git_url: https://github.com/bryanwweber/pychempath.git
    git_rev: "master"

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        # - cantera

# Conda cannot install cantera into the test environment and cannot
# check that cantera is installed already, so these have to be
# commented out until a solution is devised.
# test:
#     imports:
#         - uconnrcmpy

about:
    home: https://github.com/bryanwweber/pychempath
    license: MIT
    summary: Chemical path analysis using Cantera
