package:
    name: cantera
    version: "2.3.0a1"
source:
    git_url: https://github.com/Cantera/cantera.git
    # git_tag: v2.2.0
build:
    number: 0
requirements:
    build:
      - python
      - numpy
      - cython
    run:
      - python
      - numpy
test:
    imports:
      - cantera
