{% set name = "pandoc-attributes" %}
{% set version = "0.1.7" %}
{% set sha256 = "69221502dac74f5df1317011ce62c85a83eef5da3b71c63b1908e98224304a8c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pandocfilters >=1.4.0

test:
  imports:
    - pandocattributes

about:
  home: https://github.com/tomduck/pandoc-eqnos
  license: GPL-3.0
  summary: 'A pandoc filter for numbering equations and equation references.'
