package:
  name: cerberus
  version: "0.9.2"

source:
  fn: Cerberus-0.9.2.tar.gz
  url: https://pypi.python.org/packages/c1/7a/65f3aa48279cda81208ccca4c932e63fedaf02f80f1fb6a482a7b8d8f239/Cerberus-0.9.2.tar.gz
  md5: c0d7830016f6ae632ecb7492e28d1c65
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cerberus = cerberus:main
    #
    # Would create an entry point called cerberus that calls cerberus.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - cerberus
    - cerberus.tests

  commands:
      - python -m unittest -v cerberus.tests.tests


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/nicolaiarocci/cerberus
  license: ISC License (ISCL)
  summary: 'Lightweight, extensible schema and data validation tool for Python dictionaries.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
