package:
  name: scons
  version: "2.5.0"

source:
  fn: scons-2.5.0.tar.gz
  url: https://pypi.python.org/packages/source/S/SCons/scons-2.5.0.tar.gz
  md5: bda5530a70a41a7831d83c8b191c021e

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

about:
  home: http://www.scons.org/
  license: MIT
  summary: 'Open Source next-generation build tool.'
